export const CREATE_USER_SUCCESS = 'CREAT_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREAT_USER_FAILURE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
