export const CREATE_USER_SUCCESS = 'CREAT_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREAT_USER_FAILURE';

export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_USER_ME_SUCCESS = 'GET_USER_ME_SUCCESS';
export const GET_USER_ME_FAILURE = 'GET_USER_ME_FAILURE';

export const GET_PEOPLE_SUCCESS = 'GET_PEOPLE_SUCCESS';
export const GET_PEOPLE_FAILURE = 'GET_PEOPLE_FAILURE';
